import { MessageCircle, Paperclip } from 'lucide-react';
import AttachmentGrid from './AttachmentGrid';
import { AreaBadge, CategoryBadge, SolvedBadge, TagPill, UrgencyBadge } from './Badges';
import HelpfulButton from './HelpfulButton';
import { relativeTime } from '../utils/format';
export default function PostCard({ post,onHelpful,voting=false }){
 const preview=post.body.length>220?`${post.body.slice(0,220)}…`:post.body; const count=post.post_attachments?.length||0;
 return <article className="feed-card"><div className="flex gap-3"><div className="hidden sm:block"><HelpfulButton count={post.helpful_count} active={post.has_helpful_vote} onClick={()=>onHelpful(post.id)} disabled={voting}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-gray-500"><span className="font-bold text-gray-900">{post.anonymous_name}</span><span>•</span><span>{relativeTime(post.created_at)}</span><span>•</span><span>{post.area}</span></div><a href={`#/post/${post.id}`} className="mt-2 block text-lg font-bold leading-snug text-gray-950 hover:text-orange-700 sm:text-xl">{post.title}</a><p className="mt-2 line-clamp-3 text-sm leading-6 text-gray-700">{preview}</p><AttachmentGrid attachments={post.post_attachments||[]} compact/><div className="mt-3 flex flex-wrap items-center gap-2"><SolvedBadge solved={post.is_solved}/><CategoryBadge category={post.category}/><UrgencyBadge urgency={post.urgency}/><AreaBadge area={post.area}/>{count?<span className="pill"><Paperclip className="h-3.5 w-3.5"/>{count}</span>:null}</div>{post.tags?.length?<div className="mt-3 flex flex-wrap gap-2">{post.tags.map((tag)=><TagPill key={tag} tag={tag}/>)}</div>:null}<div className="mt-3 flex flex-wrap items-center gap-2 text-sm font-semibold text-gray-600"><div className="sm:hidden"><HelpfulButton count={post.helpful_count} active={post.has_helpful_vote} onClick={()=>onHelpful(post.id)} disabled={voting}/></div><a href={`#/post/${post.id}`} className="inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 hover:bg-gray-100"><MessageCircle className="h-4 w-4"/>{post.reply_count} {post.reply_count===1?'reply':'replies'}</a><a href={`#/post/${post.id}`} className="rounded-full px-3 py-1.5 hover:bg-gray-100">Open</a></div></div></div></article>
}
